# Generated by Django 2.1.5 on 2019-01-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(max_length=1000)),
                ('sender', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('attachment_location', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='processedemail',
            unique_together={('message_id', 'category')},
        ),
    ]
