# Generated by Django 2.1.5 on 2019-01-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('user_id', models.CharField(max_length=1000)),
                ('message_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(max_length=1000)),
                ('sender', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('attachment_location', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
    ]
